/**
 * KYC-01 Phase 4A.2B — the single shared KYC-case-creation implementation.
 *
 * Extracted from `routes/handoffs.ts` (Phase 1's own inline case-creation logic), which is the
 * ONLY route that created a `kyc_case` row before this phase. `routes/roster-sync.ts` (this
 * phase's own new route) is the second, and last, caller — both now go through this ONE function,
 * never a duplicated INSERT/checklist/audit sequence.
 *
 * `caseId` is generated by the CALLER, not here — `routes/handoffs.ts` needs the id BEFORE this
 * function runs (to publish its own `kyc1.handoff_received` event first, in the same transaction,
 * with the case id already in its metadata — see that file's own header comment for why audit
 * ORDERING is part of its accepted, behaviour-preserved contract). `routes/roster-sync.ts` mints
 * one id per missing anchor in its own loop.
 *
 * AUDIT SEPARATION (deliberate, approved Phase 4A.2B scope): this function publishes
 * `kyc1.case_created` ONLY. It never publishes `kyc1.handoff_received` — that event describes a
 * fact specific to the handoff route's own trigger (an operator/orchestrator handoff arrived),
 * which is simply untrue for a case `roster-sync` creates from CLT-01's own roster. Emitting it
 * from here would misrepresent roster-sync's own provenance in the audit trail.
 *
 * Always called from inside an ALREADY-OPEN transaction (`withTransaction`'s own `PoolClient`) —
 * this function never opens or commits its own transaction, so both callers control the exact
 * transaction boundary (and, for roster-sync, the all-or-nothing atomicity across multiple calls).
 */
import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { publishAudit } from "@aix/foundation";
import {
  DEFAULT_CHECKLIST_BY_CASE_TYPE,
  normalizeChecklistItemRow,
  normalizeKycCaseRow,
  type ChecklistItemRow,
  type KycCaseRow,
  type KycCaseType,
} from "./kyc-case.js";

export interface CreateKycCaseInput {
  caseId: string;
  applicationId: string;
  caseType: KycCaseType;
  clientId: string | null;
  partyId: string | null;
  createdFromHandoffId: string | null;
  requestId: string | null;
  correlationId: string | null;
  actorId: string;
}

export interface CreateKycCaseResult {
  caseRow: KycCaseRow;
  checklistRows: ChecklistItemRow[];
}

export async function createKycCaseWithChecklist(client: PoolClient, input: CreateKycCaseInput): Promise<CreateKycCaseResult> {
  const checklistEntries = DEFAULT_CHECKLIST_BY_CASE_TYPE[input.caseType];

  const insertedCase = await client.query<KycCaseRow>(
    `INSERT INTO kyc1.kyc_case
       (case_id, application_id, client_id, party_id, case_type, created_from_handoff_id, request_id, correlation_id)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
     RETURNING case_id, application_id, client_id, party_id, case_type, status, current_outcome_status, current_outcome_id, created_from_handoff_id, created_at_utc, updated_at_utc`,
    [input.caseId, input.applicationId, input.clientId, input.partyId, input.caseType, input.createdFromHandoffId, input.requestId, input.correlationId],
  );

  const checklistRows: ChecklistItemRow[] = [];
  for (const entry of checklistEntries) {
    const checklistItemId = "kyc1item_" + randomUUID();
    const inserted = await client.query<ChecklistItemRow>(
      `INSERT INTO kyc1.document_checklist_item (checklist_item_id, case_id, document_type, required)
       VALUES ($1,$2,$3,$4)
       RETURNING checklist_item_id, case_id, document_type, required, status, evidence_ref, evidence_hash, expiry_date, verification_result_id, created_at_utc, updated_at_utc`,
      [checklistItemId, input.caseId, entry.document_type, entry.required],
    );
    checklistRows.push(normalizeChecklistItemRow(inserted.rows[0]!));
  }

  await publishAudit(client, {
    event_type: "kyc1.case_created",
    source_module: "KYC-01",
    actor_id: input.actorId,
    actor_type: "service",
    entity_type: "kyc_case",
    entity_id: input.caseId,
    severity: "medium",
    action: "kyc_case.create",
    result: "success",
    metadata: {
      case_id: input.caseId,
      application_id: input.applicationId,
      case_type: input.caseType,
      checklist_item_ids: checklistRows.map((c) => c.checklist_item_id),
    },
  });

  return { caseRow: normalizeKycCaseRow(insertedCase.rows[0]!), checklistRows };
}
